---
- name: Deploy with docker compose 
  hosts: deployment-vm
  become: true
  tasks:
    - name: Ensure Docker Compose directory exists
      file:
        path: /opt/app
        state: directory

    - name: Generate docker-compose.yml from template
      template:
        src: ../templates/docker-compose.j2
        dest: /opt/app/docker-compose.yml
        mode: '0644'
    
    - name: Docker Login to GHCR
      shell: echo "$GITHUB_TOKEN" | docker login ghcr.io -u "{{ github_user }}" --password-stdin
      no_log: true
      environment:
        GITHUB_TOKEN: "{{ lookup('env','GITHUB_TOKEN') }}"


    - name: Pull backend image
      shell: docker pull {{ backend_image }}

    - name: Pull frontend image
      shell: docker pull {{ frontend_image }}

    - name: Run docker-compose up
      shell: docker-compose up -d --remove-orphans
      args:
        chdir: /opt/app