---
  
- name: install postgres
  hosts: all 
  become: yes 
  become_user: root

  tasks:   
    - name: install postgres  and pip packages
      apt:
        name: postgresql, python3-pip
        state: present
        update_cache: yes


      
    - name: edit postgres.conf 
      lineinfile:
        path: /etc/postgresql/16/main/postgresql.conf
        regexp: '^listen_addresses ='
        line: "listen_addresses='*'"
      notify: 
        restart postgres

      
    - name: edit pg_hba.conf
      lineinfile:
        path: /etc/postgresql/16/main/pg_hba.conf
        line: "host  all all 0.0.0.0/0 md5"
        create: yes
      notify: 
        restart postgres


      
    - name: install python pg module
      command: pip3 install psycopg2-binary --break-system-packages

    - name: create postgres user
      postgresql_user:
        name: myuser
        password: 'pass12345'
      become: yes
      become_user: postgres


      
    - name: create postgres database
      postgresql_db:
        name: mydb
        owner: myuser
      become: yes
      become_user: postgres

  handlers:
    - name: restart postgres
      service:
        name: postgresql
        state: restarted