---
azure-hosts:
  hosts:
    deployment-vm:
      ansible_host: deployment
      
azurehosts:
  hosts:
    spring:
      ansible_host: dev-vm-1
    vue:
      ansible_host: frontend
      
dbservers:
  hosts:
    db:
      ansible_host: dbservers